// my-first-web-portfolio/src/routes/+page.svelte
<script>
	import { onMount } from 'svelte';
	import { globalDataLoadingDuration } from '../lib/store/store';
	import Loader from '../lib/components/Loader.svelte';
	import { mounted } from '../lib/store/store';

	const loadingMessage = 'Home.';
	$mounted = false;

	onMount(() => {
		const timer = setTimeout(() => {
			$mounted = true;
			console.log($mounted + "in project")
		}, $globalDataLoadingDuration);
		return () => clearTimeout(timer);
	});
</script>

<Loader message={loadingMessage}></Loader>

<div class="flex flex-col justify-start" class:hide={!$mounted}>
	<div class="w-full p-28 flex flex-col justify-center items-start gap-5 pb-20">
			<div class="flex flex-col justify-start items-start gap-5">
				<h3 class="w-80 text-lg text-gray-300">
					Welcome to John Smith's World of Web Wizardry! I'm John, a skilled web developer
					passionate about creating stunning online experiences. Explore my portfolio and discover
					how I can bring your digital dreams to life.
				</h3>
				<button class="bg-stone-950 rounded-xl px-5 py-3 hover:bg-slate-300 animate-pulse text-gray-300 hover:text-stone-800"
					><a href="/projects"><span class="font-mono">PROJECTS</span></a></button
				>
			</div>
	</div>

	<div class="text-container flex flex-col items-center justify-end pb-24 overflow-hidden">
		<div class="whitespace-nowrap text-inner-wrapper overflow-hidden text-white">
			<div class="text-slides">
				<h1 class="text-[188px] ">John Smith - Prospective Web Developer</h1>
			</div>
			<div class="text-slides">
				<h1 class="text-[188px] ">John Smith - Prospective Web Developer</h1>
			</div>
			<div class="text-slides">
				<h1 class="text-[188px]">John Smith - Prospective Web Developer</h1>
			</div>
		</div>
	</div>
</div>

<style>
	.text-container {
		height: auto;
	}

	.text-inner-wrapper:hover .text-slides {
		animation-play-state: paused;
	}
	.text-slides {
		display: inline-block;
		animation: slide 25s infinite linear;
		padding-right: 10em;
		font-family: DMSans, Arial, Helvetica, sans-serif;
	}

	button {
		transition-property: transform, color, background-color;
		transition-duration: 2s;
	}

	button:hover {
		transform: translateX(20px);
		animation-play-state: paused;
        border-bottom-right-radius: 100px;
        border-top-right-radius: 100px;
	}
	.hide {
		display: none;
	}

	@keyframes slide {
		from {
			transform: translateX(0%);
		}
		to {
			transform: translateX(-100%);
		}
	}
</style>

// src/routes/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router';

import { Button } from '@/components/ui/button';

export const Route = createFileRoute('/')({
	staticData: { loaderLabel: 'Home.' },
	component: HomePage
});

const MARQUEE_TEXT = 'Tony T Li - Prospective Software Developer';

function HomePage() {
	return (
		<div className="flex min-h-screen flex-col justify-start">
			<div className="flex w-full flex-col items-start justify-center gap-5 p-28 pb-20 desktop:pt-32 desktop:pb-24 desktop:pl-44">
				<div className="flex flex-col items-start justify-start gap-5">
					<h3 className="text-lg text-gray-300 tablet:w-80">
						Welcome to Tony Tuocheng Li's World of Tech Wizardry! I'm Tony, a prospective Software
						developer passionate about creating stunning online experiences. Explore my portfolio
						and discover how I can bring your digital dreams to life.
					</h3>
					<Button
						asChild
						className="h-auto animate-pulse rounded-xl bg-stone-950 px-5 py-3 text-base font-normal text-gray-300 transition-[transform,color,background-color] duration-1000 hover:translate-x-5 hover:rounded-r-[100px] hover:bg-slate-300 hover:text-stone-800 hover:[animation-play-state:paused]"
					>
						<Link to="/projects">
							<span className="font-mono">PROJECTS</span>
						</Link>
					</Button>
				</div>
			</div>

			<div className="flex h-auto flex-col items-center justify-end overflow-hidden pb-24">
				<div className="overflow-hidden whitespace-nowrap text-white" aria-label={MARQUEE_TEXT}>
					{[0, 1, 2].map((copy) => (
						<div
							key={copy}
							aria-hidden
							className="inline-block animate-marquee pr-[10em] font-titillium"
						>
							<h1 className="text-[188px] desktop:text-[220px]">{MARQUEE_TEXT}</h1>
						</div>
					))}
				</div>
			</div>
		</div>
	);
}
