// src/components/contact-form.tsx
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { site } from '@/data/site';

// Underline-only fields, as in the original design
const fieldClass =
	'h-auto rounded-none border-0 border-b border-black/15 bg-transparent px-0 py-1 text-2xl placeholder:text-gray-400/25 focus-visible:ring-0 dark:border-white/20 dark:bg-transparent';

const otherContacts = [
	{ href: `mailto:${site.email}`, label: site.email },
	{ href: site.github, label: 'Github' },
	{ href: site.linkedin, label: 'Linkedin' }
];

/** Contact page body. Plain HTML form POST to getform.io (no JS submit handling). */
export function ContactForm() {
	return (
		<div className="flex animate-page flex-col items-center justify-center pb-12 tablet:py-16 laptop:min-h-screen laptop:py-24">
			<div className="px-24 pt-12 transition-[padding,transform] duration-1000 laptop:py-24">
				<h2 className="font-titillium text-3xl text-neutral-900 opacity-75 transition-[font-size,padding] duration-1000 tablet:text-6xl laptop:text-8xl desktop:px-14 desktop:text-9xl dark:text-white">
					Let's start on something incredible together
				</h2>
			</div>

			<div className="flex flex-col items-center justify-between pt-8 pb-12 text-neutral-900 tablet:grid tablet:grid-cols-4 tablet:items-start dark:text-white">
				<div className="col-span-3 flex flex-col items-center justify-center text-2xl">
					<form action={site.contactFormAction} method="POST" className="w-60">
						<div className="flex flex-col items-center justify-center gap-8">
							<div className="flex w-full flex-col gap-4">
								<Label htmlFor="name" className="text-2xl font-normal">
									Name:
								</Label>
								<Input
									required
									id="name"
									type="text"
									name="name"
									placeholder="Tony Li"
									autoComplete="on"
									className={fieldClass}
								/>
							</div>
							<div className="flex w-full flex-col gap-4">
								<Label htmlFor="email" className="text-2xl font-normal">
									Email:
								</Label>
								<Input
									required
									id="email"
									type="email"
									name="email"
									placeholder={site.email}
									autoComplete="on"
									className={fieldClass}
								/>
							</div>
							<div className="flex w-full flex-col items-start gap-4">
								<Label htmlFor="message" className="text-2xl font-normal">
									Message:
								</Label>
								<Textarea
									id="message"
									name="message"
									placeholder="Hello Tony, I would like..."
									className={`${fieldClass} min-h-48`}
								/>
							</div>
							{/* Honeypot field to deter spam bots */}
							<input type="hidden" name="_gotcha" style={{ display: 'none' }} />

							<Button
								type="submit"
								className="h-auto rounded-lg bg-gray-600 p-2 font-mono text-lg font-normal text-white transition-transform duration-2000 hover:translate-x-5 hover:animate-button-effect hover:bg-gray-600"
							>
								Lets chat!
							</Button>
						</div>
					</form>
				</div>
				<div className="flex flex-col items-start justify-center gap-2 pt-16 tablet:pt-2">
					<h1 className="border-b border-black/15 pb-2 dark:border-white/20">Other Contacts:</h1>
					{otherContacts.map((contact) => (
						<span
							key={contact.label}
							className="py-2 hover:animate-bounce hover:border-b hover:border-black/40 dark:hover:border-white/50"
						>
							<a className="py-2" href={contact.href} target="_blank" rel="noreferrer">
								{contact.label}
							</a>
						</span>
					))}
				</div>
			</div>
		</div>
	);
}

// my-first-web-portfolio/src/lib/components/ContactForm.svelte
<script>
    import { mounted } from "../store/store";
</script>

<div class="contact-main-container flex flex-col justify-center items-center desktop:min-h-fit pb-12" class:hide={!$mounted}>
	<div class="contact-page-title-div px-24 pt-12 tablet:py-16 laptop:py-24">
		<h2 class="contact-page-title text-3xl laptop:text-8xl tablet:text-6xl text-white opacity-75 desktop:text-9xl desktop:px-14">Let's start on something incredible together</h2>
	</div>

	<div
		class=" flex flex-col tablet:grid tablet:grid-cols-4 justify-between items-center tablet:items-start pt-8 pb-12 text-white"
	>
		<div class="flex flex-col col-span-3 text-2xl justify-center items-center">
			<form action="https://getform.io/f/pagxpqeb" method="POST">
				<div class="flex flex-col gap-8 items-center justify-center">
					<div class="flex flex-col form-col gap-4">
						<label for="name">Name:</label>
						<input
							required
							id="name"
							class="bg-transparent"
							type="text"
							name="name"
							placeholder="Tony Li"
							autocomplete="on"
						/>
					</div>
					<div class="flex flex-col form-col gap-4">
						<label for="email">Email:</label>
						<input required id="email" type="email" name="email" placeholder="leetony347@yahoo.com" autocomplete="on" />
					</div>
					<div class="flex flex-col form-col gap-4 items-start w-full">
						<label for="message">Message:</label>
						<textarea
							id="message"
							class="min-h-48"
							type="text"
							name="message"
							placeholder="Hello Tony, I would like..."
						></textarea>
					</div>
					<!-- add hidden Honeypot input to prevent spams -->
					<input type="hidden" name="_gotcha" style="display:none !important" />

					<button class="bg-gray-600 font-mono p-2 rounded-lg text-lg" type="submit"
						>Lets chat!</button
					>
				</div>
			</form>
		</div>
		<div class="flex flex-col pt-16 tablet:pt-2 justify-center items-start gap-2">
			<h1 class="pb-2">Other Contacts:</h1>
			<span class="py-2 other-contact-link hover:animate-bounce hover:"
				><a class="py-2" href="mailto:leetony347@yahoo.com" target="_blank">leetony347@yahoo.com</a></span
			>
			<span class="py-2 other-contact-link hover:animate-bounce"
				><a class="py-2" href="https://github.com/Todaricli" target="_blank">Github</a></span
			>
			<span class="py-2 other-contact-link hover:animate-bounce"
				><a class="py-2" href="https://www.linkedin.com/in/tuocheng-li-b86b59231/" target="_blank">Linkedin</a
				></span
			>
		</div>
	</div>
</div>

<style>
	.hide {
		display: none;
	}

	input,
	textarea {
		border-bottom: 1px solid rgba(255, 255, 255, 0.2);
	}

	h1 {
		border-bottom: 1px solid rgba(255, 255, 255, 0.2);
	}

	.form-col input,
	textarea {
		background: transparent !important;
	}
	textarea:focus,
	input:focus {
		outline: none;
	}

	button:hover {
		animation: button-effect 0.5s forwards linear;
		transform: translateX(20px);
	}

	button {
		transition: transform 2s;
	}

	::placeholder {
		opacity: 0.25;
	}

	.contact-page-title {
		font-family: DMSans, Arial, Helvetica, sans-serif;
		transition-property: font-size, padding, text-wrap;
		transition-duration: 1s;
	}
	.other-contact-link:hover {
		border-bottom: 1px solid rgba(255, 255, 255, 0.5);
	}
	.contact-page-title-div {
		transition-property: padding, transform;
		transition-duration: 1s;
	}
    .contact-main-container {
        animation: page-effect 1s forwards linear;
    }

	@keyframes button-effect {
		0% {
		}
		50% {
			border-radius: 35%;
			padding: 6px;
			background-color: aliceblue;
			color: gray;
		}
		100% {
			border-top-right-radius: 50%;
			border-bottom-right-radius: 50%;
			padding: 12px;
			background-color: whitesmoke;
			color: black;
		}
	}
</style>
